[package]
name = "rover"
version = "0.1.0"
authors = ["Wojciech Kępka <wojtek.kepka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { version = "0.7", features = ["im"] }